name: Continuous Integration and Deployment

on:
  push:
    branches:
      - IAT-4
  pull_request:
    branches:
      - IAT-4

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test -DskipTests

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Upload Allure Results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Convert Allure Report to HTML
        run: |
          allure generate allure-results --clean -o allure-report
          ls -l allure-report  # Optional: List files in allure-report for verification

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd allure-report
          git config user.email "kashyap.dave@krishtechnolabs.com"
          git config user.name "KashyapDave95"
          git add .
          git commit -m "Deploy Allure report to GitHub Pages"
          git push origin gh-pages