name: CI/CD

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Tests and Generate Allure Report
        run: |
          mvn clean test -Dallure.results.directory=allure-results
          mvn allure:report

      - name: Upload Allure Results as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Download Allure results
        uses: actions/download-artifact@v2
        with:
            name: allure-results
            path: allure-results 

      - name: Generate Allure HTML Report
        run: |
          allure generate D:\a\Bateel_Automation\Bateel_Automation\allure-results --clean -o allure-report-html

      - name: Set Allure HTML report link 
        if: success()
        run: |
          echo "::set-output name=allure_html_report_link::file://${{ github.workspace }}/allure-report-html/index.html"

      - name: Open Allure HTML report
        if: success()
        run: |
            start "" "D:\\a\\Bateel_Automation\\Bateel_Automation\\allure-report-html\\index.html"