name: CI/CD

on:
  push:
    branches:
      - 'IAT-4'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Tests and Generate Allure Report
        run: |
          mvn clean test || true
          mvn allure:report || true
        continue-on-error: true

      - name: Publish Allure Report to GitHub Pages
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report-html
          touch allure-report-html/.nojekyll
        continue-on-error: true

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./allure-report-html
          publish_branch: gh-pages 