name: Updated flow
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          version: 94.0.4606.61
      - name: Download ChromeDriver
        run: |
          mkdir drivers
          curl -SL -o drivers/chromedriver.zip https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip
          unzip -l drivers/chromedriver.zip
          unzip drivers/chromedriver.zip -d drivers/
          chmod +x drivers/chromedriver
      - name: Run pom.xml file
        run: |
          if [ ! -f "pom.xml" ]; then
            cp pom.xml .
          fi
      - name: Resolve Maven dependencies
        run: mvn dependency:resolve
  test:
    name: Run Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          version: 94.0.4606.61
      - name: Download ChromeDriver
        run: |
          mkdir drivers
          curl -SL -o drivers/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip -l drivers/chromedriver.zip
          unzip drivers/chromedriver.zip -d drivers/
          chmod +x drivers/chromedriver
      - name: Run tests with WebDriver initialization
        run: mvn clean test
  allure-report:
    name: Allure Report
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
      - name: Generate Allure report
        run: mvn allure:report
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /allure-results
      - name: Get GitHub Pages URL
        id: pages_url
        run: echo "::set-output name=url::https://SohamQAKrish.github.io/Bateel_Automation/allure-results/index.html"
      - name: Display Allure report link
        run: echo "Allure report available at ${{ steps.pages_url.outputs.url }}"
